feat(PGVector): allow users to configure distance metric and HNSW index parameters for PGVector in Llama Stack YAML config (#4714)
# What does this PR do?
<!-- Provide a short summary of what this PR does and why. Link to
relevant issues if applicable. -->
This PR is responsible for extending `PGVectorVectorIOConfig` to allow
users to define distance metric and HNSW index parameters in
corresponding `config.yaml`

<!-- If resolving an issue, uncomment and update the line below -->
Closes #4713

## Test Plan
<!-- Describe the tests you ran to verify your changes with result
summaries. *Provide clear instructions so the plan can be easily
re-executed.* -->

### 1. Create config.yaml defining distance metric and HNSW parameters:

E.g. Put the vector_io section in config.yaml with other APIs

```
vector_io:
 - provider_id: ${env.PGVECTOR_DB:+pgvector}
   provider_type: remote::pgvector
   config:
     host: ${env.PGVECTOR_HOST:=localhost}
     port: ${env.PGVECTOR_PORT:=5432}
     db: ${env.PGVECTOR_DB:=testvectordb}
     user: ${env.PGVECTOR_USER:=user}
     password: ${env.PGVECTOR_PASSWORD:=password}
     distance_metric: COSINE
     hnsw_m: 16
     hnsw_ef_construction: 64
     persistence:
       namespace: vector_io::pgvector
       backend: kv_default
```

> Appreciate how here we configured distance_metric: COSINE, hnsw_m: 16
and hnsw_ef_construction: 64

### 2. Run Llama Stack server:

`llama stack run starter`

Logs:

```
INFO     2026-01-23 12:14:29,611 llama_stack.providers.remote.vector_io.pgvector.pgvector:400 vector_io::pgvector:
         Initializing PGVector memory adapter with config: {'host': 'localhost', 'port': 5432, 'db': 'testvectordb',
         'user': 'user', 'distance_metric': 'COSINE', 'hnsw_m': 16, 'hnsw_ef_construction': 64, 'persistence':
         {'namespace': 'vector_io::pgvector', 'backend': 'kv_default'}, 'password': '******'}

```

### 3. HNSW index with parameters was created and distance metric was
applied:

```
testvectordb=# \z
                                               Access privileges
 Schema |                    Name                    | Type  | Access privileges | Column privileges | Policies
--------+--------------------------------------------+-------+-------------------+-------------------+----------
 public | metadata_store                             | table |                   |                   |
 public | vs_vs_7cf59756_a775_449c_9acc_784061eb14b7 | table |                   |                   |
(2 rows)

testvectordb=# SELECT indexname, indexdef
FROM pg_indexes
WHERE indexdef LIKE '%hnsw%';
                      indexname                      |                                                                                              indexdef
-----------------------------------------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 vs_vs_7cf59756_a775_449c_9acc_784061eb14b7_hnsw_idx | CREATE INDEX vs_vs_7cf59756_a775_449c_9acc_784061eb14b7_hnsw_idx ON public.vs_vs_7cf59756_a775_449c_9acc_784061eb14b7 USING hnsw (embedding vector_cosine_ops) WITH (m='16', ef_construction='64')
(1 row)

testvectordb=#
```

### 4. Proper error handling is enabled when user interacts with
config.yaml to configure PGVector:

E.g. User defines `distance_metric: DUMMY` in config.yaml

Llama Stack's response:

```
pydantic_core._pydantic_core.ValidationError: 1 validation error for PGVectorVectorIOConfig
distance_metric
  Input should be 'COSINE', 'L2', 'L1' or 'INNER_PRODUCT' [type=literal_error, input_value='DUMMY', input_type=str]
    For further information visit https://errors.pydantic.dev/2.11/v/literal_error
```


### 5. Different distance metric is applied (in this case user uses L2
Euclidean distance metric):

Llama Stack logs:

```
INFO     2026-01-23 12:49:58,192 llama_stack.providers.remote.vector_io.pgvector.pgvector:400 vector_io::pgvector:
         Initializing PGVector memory adapter with config: {'host': 'localhost', 'port': 5432, 'db': 'testvectordb',
         'user': 'user', 'distance_metric': 'L2', 'hnsw_m': 16, 'hnsw_ef_construction': 64, 'persistence': {'namespace':
         'vector_io::pgvector', 'backend': 'kv_default'}, 'password': '******'}
```

**Different index is created with corresponding index operator class
vector_l2_ops:**

```
testvectordb=# SELECT indexname, indexdef
FROM pg_indexes
WHERE indexdef LIKE '%hnsw%';
                      indexname                      |                                                                                            indexdef
-----------------------------------------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
 vs_vs_b9235301_7b85_412a_9417_ee0b485c3e7c_hnsw_idx | CREATE INDEX vs_vs_b9235301_7b85_412a_9417_ee0b485c3e7c_hnsw_idx ON public.vs_vs_b9235301_7b85_412a_9417_ee0b485c3e7c USING hnsw (embedding vector_l2_ops) WITH (m='16', ef_construction='64')
(1 row)

testvectordb=#
```

SQL Query plan:

```
Limit  (cost=9.44..14.93 rows=50 width=40) (actual time=0.309..0.313 rows=1.00 loops=1)
  Buffers: shared hit=42
  InitPlan 1
    ->  Limit  (cost=0.00..0.03 rows=1 width=32) (actual time=0.020..0.022 rows=1.00 loops=1)
          Buffers: shared hit=1
          ->  Seq Scan on vs_vs_b9235301_7b85_412a_9417_ee0b485c3e7c vs_vs_b9235301_7b85_412a_9417_ee0b485c3e7c_1  (cost=0.00..14.30 rows=430 width=32) (actual time=0.019..0.020 rows=1.00 loops=1)
                Buffers: shared hit=1
  ->  Index Scan using vs_vs_b9235301_7b85_412a_9417_ee0b485c3e7c_hnsw_idx on vs_vs_b9235301_7b85_412a_9417_ee0b485c3e7c  (cost=9.41..56.60 rows=430 width=40) (actual time=0.307..0.309 rows=1.00 loops=1)
        Order By: (embedding <-> (InitPlan 1).col1)
        Index Searches: 0
        Buffers: shared hit=42
Planning:
  Buffers: shared hit=133
Planning Time: 2.064 ms
Execution Time: 0.432 ms
```

**L2 distance metric and HNSW index with proper operator class were
successfully used during vector search reflecting user's configuration
in config.yaml**


### 6. If user doesn’t specify distance metric and HNSW parameters, then
default values are being applied:

```
INFO     2026-01-23 14:47:24,870 llama_stack.providers.remote.vector_io.pgvector.pgvector:399 vector_io::pgvector:
         Initializing PGVector memory adapter with config: {'host': 'localhost', 'port': 5432, 'db': 'testvectordb',
         'user': 'user', 'distance_metric': 'COSINE', 'hnsw_m': 16, 'hnsw_ef_construction': 64, 'persistence':
         {'namespace': 'vector_io::pgvector', 'backend': 'kv_default'}, 'password': '******'}
```





<!-- For API changes, include:
1. A testing script (Python, curl, etc.) that exercises the new/modified
endpoints
2. The output from running your script

Example:
```python
...
...
```

Output:
```
<paste actual output here>
```
-->